# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  lefty_joint_1:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  lefty_joint_2:
    has_velocity_limits: true
    max_velocity: 2.0944
    has_acceleration_limits: false
    max_acceleration: 0
  lefty_joint_3:
    has_velocity_limits: true
    max_velocity: 2.0944
    has_acceleration_limits: false
    max_acceleration: 0
  lefty_joint_4:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: false
    max_acceleration: 0
  lefty_joint_5:
    has_velocity_limits: true
    max_velocity: 4.3633
    has_acceleration_limits: false
    max_acceleration: 0
  lefty_joint_6:
    has_velocity_limits: true
    max_velocity: 5.7596
    has_acceleration_limits: false
    max_acceleration: 0
  lefty_joint_carriage:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0