# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - lefty_joint_carriage
    - lefty_joint_1
    - lefty_joint_2
    - lefty_joint_3
    - lefty_joint_4
    - lefty_joint_5
    - lefty_joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
- name: ""
  action_ns: p26_lefty/joint_trajectory_action
  type: FollowJointTrajectory
  joints:
    - lefty_joint_carriage
    - lefty_joint_1
    - lefty_joint_2
    - lefty_joint_3
    - lefty_joint_4
    - lefty_joint_5
    - lefty_joint_6
